import { execSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { WorktreeStore } from "@pi/tasks";

function findWorktreePath(taskId: string, cwd: string): string | null {
  const candidates = [
    join(cwd, ".pi-pro", "worktrees", taskId),
    join(homedir(), ".pi-pro", "worktrees", taskId),
  ];
  for (const c of candidates) {
    if (existsSync(join(c, ".git"))) return c;
  }
  return null;
}

function git(cmd: string, cwd: string, opts: { inherit?: boolean } = {}): string {
  return execSync(cmd, { cwd, stdio: opts.inherit ? "inherit" : "pipe" }).toString().trim();
}

function which(cmd: string): boolean {
  try {
    execSync(`command -v ${cmd} 2>/dev/null`, { stdio: "pipe" });
    return true;
  } catch {
    return false;
  }
}

function buildPrBody(taskId: string, evidence: string): string {
  return [
    `## pi build ${taskId}`,
    "",
    evidence.slice(0, 2000),
    "",
    "---",
    "*Generated by pi v0.2.0*",
  ].join("\n");
}

export async function runMerge(taskId: string): Promise<void> {
  if (!/^tsk_[a-z0-9]{4,32}$/.test(taskId)) {
    console.error(`✗ invalid taskId: ${taskId}`);
    console.error(`  taskId must match /^tsk_[a-z0-9]{4,32}$/`);
    process.exit(1);
  }

  const cwd = process.cwd();
  const wt = findWorktreePath(taskId, cwd);
  if (!wt) {
    console.error(`✗ no worktree found for ${taskId}`);
    console.error(`  searched: ${cwd}/.pi-pro/worktrees/${taskId}`);
    console.error(`           ${homedir()}/.pi-pro/worktrees/${taskId}`);
    console.error(`  run a successful build first: pi "<task>"`);
    process.exit(1);
  }

  console.log(`merging ${taskId} → main`);
  console.log(`  worktree: ${wt}`);

  // Read evidence from replay if available
  const evidenceFile = join(wt, ".pi-pro", "evidence.txt");
  const evidence = existsSync(evidenceFile) ? readFileSync(evidenceFile, "utf8") : "(no evidence recorded)";

  try {
    const branch = git("git rev-parse --abbrev-ref HEAD", wt);
    console.log(`  branch:   ${branch}`);

    // Try to push branch first
    console.log("  pushing branch...");
    try {
      git("git push -u origin " + branch, wt, { inherit: true });
    } catch {
      // branch may not have remote tracking yet
    }

    // Switch to main and rebase
    const mainBranch = git("git rev-parse --verify main 2>/dev/null && echo main || echo master", wt);
    console.log(`  rebasing onto ${mainBranch}...`);
    git(`git checkout ${mainBranch}`, wt, { inherit: true });
    try {
      git("git pull --rebase origin " + mainBranch, wt, { inherit: true });
    } catch {
      // no upstream or no changes
    }

    console.log(`  merging ${branch} into ${mainBranch} (--no-ff)...`);
    git(`git merge --no-ff ${branch} -m "merge: ${taskId}"`, wt, { inherit: true });

    console.log("  pushing to origin...");
    git(`git push origin ${mainBranch}`, wt, { inherit: true });

    console.log(`  ✓ merged ${branch} into ${mainBranch}`);

    // Try to open a PR if gh is available and we're not already on main
    if (which("gh")) {
      console.log("  opening PR with gh...");
      try {
        const title = `pi ${taskId}`;
        const body = buildPrBody(taskId, evidence);
        execSync(
          `gh pr create --title ${JSON.stringify(title)} --body ${JSON.stringify(body)} --base ${mainBranch} --head ${branch}`,
          { cwd: wt, stdio: "inherit" }
        );
      } catch {
        // PR may already exist or other gh error
        console.log("  ! gh pr create failed (PR may already exist or remote doesn't support it)");
      }
    } else {
      console.log("  (gh not installed — skip PR creation)");
    }
  } catch (e) {
    console.error(`✗ merge failed: ${(e as Error).message}`);
    process.exit(1);
  }
}
