import { existsSync } from "node:fs";
import { join, basename } from "node:path";
import { spawnSync } from "node:child_process";

export interface PrBodyInput {
  taskId: string;
  title: string;
  branch: string;
  changes: string[];
  verification?: string;
}

export function buildPrTitle(title: string): string {
  const maxBody = 72;
  const prefix = "pi-pro: ";
  const body = title.length > maxBody ? title.slice(0, maxBody - 3) + "..." : title;
  return `${prefix}${body}`;
}

export function generatePrBody(input: PrBodyInput): string {
  const sections: string[] = [];
  sections.push(`## Summary\n\n${input.title}`);
  sections.push(`Task: \`${input.taskId}\` · Branch: \`${input.branch}\``);
  if (input.changes.length > 0) {
    sections.push(`## Changes\n\n${input.changes.map(c => `- [ ] ${c}`).join("\n")}`);
  }
  if (input.verification) {
    sections.push(`## Verification\n\n${input.verification}`);
  }
  sections.push(`---\nGenerated by pi-pro`);
  return sections.join("\n\n");
}

export interface WorktreeRef {
  path: string;
  branch: string;
  taskId: string;
}

export function findWorktreeForTask(taskId: string, cwd: string = process.cwd()): WorktreeRef | null {
  const expectedDir = join(cwd, ".pi-pro", "worktrees", taskId);
  if (!existsSync(expectedDir)) return null;
  const res = spawnSync("git", ["-C", expectedDir, "rev-parse", "--abbrev-ref", "HEAD"], { encoding: "utf8" });
  if (res.status !== 0) return null;
  return { path: expectedDir, branch: (res.stdout ?? "").trim(), taskId };
}

export interface MergeResult {
  pushed: boolean;
  prUrl: string | null;
  warnings: string[];
}

export async function runMerge(taskId: string, baseBranch: string = "master"): Promise<void> {
  try {
    const result = mergeTask(taskId, process.cwd(), baseBranch);
    if (result.pushed) {
      console.log(`✓ Pushed branch to origin.`);
    }
    for (const w of result.warnings) {
      console.log(`! ${w}`);
    }
    if (result.prUrl) {
      console.log(`✓ PR opened: ${result.prUrl}`);
    } else {
      console.log(`(no PR URL — open one manually if needed)`);
    }
  } catch (e) {
    console.error(`pi-pro merge ${taskId} failed: ${(e as Error).message}`);
    process.exit(1);
  }
}

export function mergeTask(taskId: string, cwd: string = process.cwd(), baseBranch: string = "master"): MergeResult {
  const warnings: string[] = [];
  const wt = findWorktreeForTask(taskId, cwd);
  if (!wt) {
    throw new Error(`No worktree found for task ${taskId} at ${join(cwd, ".pi-pro/worktrees", taskId)}`);
  }

  const rebase = spawnSync("git", ["-C", wt.path, "rebase", baseBranch], { encoding: "utf8" });
  if (rebase.status !== 0) {
    throw new Error(`Rebase onto ${baseBranch} failed: ${rebase.stderr}\nResolve conflicts and retry.`);
  }

  const push = spawnSync("git", ["-C", wt.path, "push", "-u", "origin", wt.branch], { encoding: "utf8" });
  if (push.status !== 0) {
    warnings.push(`Push to origin/${wt.branch} failed: ${push.stderr}. Run 'git push' manually after configuring the remote.`);
    return { pushed: false, prUrl: null, warnings };
  }

  const gh = spawnSync("gh", ["pr", "create", "--base", baseBranch, "--head", wt.branch, "--title", `pi-pro: ${basename(taskId)}`, "--body", "pi-pro auto-PR"], { encoding: "utf8" });
  if (gh.status !== 0) {
    warnings.push(`gh pr create failed: ${gh.stderr}. Run 'gh pr create' manually.`);
    return { pushed: true, prUrl: null, warnings };
  }

  const urlMatch = (gh.stdout ?? "").match(/https?:\/\/\S+/);
  return { pushed: true, prUrl: urlMatch ? urlMatch[0] : null, warnings };
}
